# Generated by Django 5.0.2 on 2024-05-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0005_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('bulletin', 'author')},
        ),
    ]
