# Generated by Django 5.0.2 on 2024-05-04 22:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0010_response_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
